### ISSUE TITLE
has_many uuid instead of id

### ISSUE THREAD

**Issue by maxrosecollins** [fast-jsonapi/fast_jsonapi#76] opened 2020-04-17 09:03 UTC
How can I specify to use the uuid instead of the id on a relationship?
In the `ResultSerializer` I have
```
set_id { |object| object.uuid }
```
Below is the expected result

```
has_many :results
```

```
"relationships": {
                "results": {
                    "data": [
                        {
                            "id": ""6c2d2f8d-341d-4aee-a250-eae196ca197a",
                            "type": ""result
                        },
```

But my result is 
```
"relationships": {
                "results": {
                    "data": [
                        {
                            "id": "1",
                            "type": "result"
                        },
                        {
                            "id": "2",
                            "type": "result"
                        },
```

If I call the serializer directly, then I can see the following

```
[
   "data": {
                        "id": "a96cfa2d-ae77-43a5-b6ba-4720b100dcff",
                        "type": "result",
                        "attributes": {
                        etc
```

**Comment by maxrosecollins** [comment] 2020-04-17 09:52
I see this could be a duplicate of [53](https://github.com/fast-jsonapi/fast_jsonapi/issues/53)

I tried the workaround 
```
has_many :results, serializer: ResultSerializer, id_method_name: :uuid do |result|
    result.uuid
end
``
this returns
```
 "relationships": {
                "results": {
                    "data": []
                }
            }
```
so that doesn't work for me

**Comment by stas** [comment] 2020-04-28 13:05
@maxrosecollins this indeed is a duplicate of #53 

I'll close it to keep track of it in the other issue. Sorry for the late reply :bow:

**Closed by stas** 2020-04-28 13:05 UTC

**Comment by maxrosecollins** [comment] 2020-04-28 13:20
@stas No problem. I'll keep an eye on it.
